from pathlib import Path
import hashlib,json,zipfile,py_compile,tempfile

SRC=Path("packages/LONGFORM_FACTORY_RESULT_FOCUS_FIX_1_14_9.lfupdate.zip")
OUT=Path("packages/LONGFORM_FACTORY_GREENLIGHT_REVIEW_1_14_10.lfupdate.zip")
def sha(b): return hashlib.sha256(b).hexdigest()
with zipfile.ZipFile(SRC) as z: files={n:z.read(n) for n in z.namelist()}

# Patch JP_BTS v1.1 with explicit Greenlight review action.
ap="payload/adapters/channels/jp_bts/production_adapter_v11.py"
s=files[ap].decode()
insert='''

    def review_greenlight(self, episode_id, decision, note=""):
        ep=self._episode_dir(episode_id)
        m=self._load_manifest(ep)
        if self._stage(m)!="GREENLIGHT":
            raise RuntimeError("Episode is not in GREENLIGHT")
        if self._state(m)!="NEEDS_REVIEW":
            raise RuntimeError("GREENLIGHT is not awaiting review")
        decision=str(decision or "").upper()
        if decision not in {"APPROVE","HOLD","REJECT"}:
            raise ValueError("decision must be APPROVE, HOLD, or REJECT")
        d=self._disc(m)
        winner=d.get("winner_candidate_id")
        review={"decision":decision,"note":str(note or ""),"winner_candidate_id":winner,
                "discovery_gate_status":d.get("status")}
        m["greenlight_review"]=review
        if decision=="APPROVE":
            if d.get("status")!="DISCOVERY_PASS" or not winner:
                raise RuntimeError("Cannot approve without clean Discovery winner")
            self._set_stage(m,"GREENLIGHT","COMPLETE")
            self._set_stage(m,"EDITORIAL","READY",current=True)
        elif decision=="HOLD":
            self._set_stage(m,"GREENLIGHT","NEEDS_REVIEW",current=True)
        else:
            self._set_stage(m,"GREENLIGHT","REJECTED",current=True)
        self._save_manifest(ep,m)
        return {"ok":True,"message":"Greenlight "+decision.lower(),
                "decision":decision,"winner_candidate_id":winner,
                "current_stage":self._stage(m),"current_state":self._state(m)}
'''
# Insert before end of class (file ends after _import_result); append at class indentation.
if "def review_greenlight(" not in s:
    s=s.rstrip()+insert+"\n"
files[ap]=s.encode()

boot="payload/control_center_v114_bootstrap.py"
bt=files[boot].decode()
bt=bt.replace('FACTORY_VERSION="1.14.9"','FACTORY_VERSION="1.14.10"')
bt=bt.replace('<div class="ver">v1.14.9</div>','<div class="ver">v1.14.10</div>')

# Runtime source is generated by bootstrap; patch API and UI text before it is written.
anchor='runtime=ROOT/"factory"/"state"/"control_center_v114_runtime.py"'
patch=r'''
# v1.14.10: expose Greenlight NEEDS_REVIEW as an explicit lifecycle review action.
if "greenlight-review-11410" not in text:
    # Add a small client-side review control to Greenlight Review detail.
    ui = r"""<script id="greenlight-review-11410">
document.addEventListener("click",async function(ev){
 const b=ev.target.closest("[data-greenlight-decision]"); if(!b)return;
 const id=b.getAttribute("data-episode-id"), decision=b.getAttribute("data-greenlight-decision");
 const res=await fetch("/api/episodes/"+encodeURIComponent(id)+"/greenlight-review",{
   method:"POST",headers:{"Content-Type":"application/json"},
   body:JSON.stringify({decision:decision,note:""})
 });
 const j=await res.json().catch(()=>({}));
 if(!res.ok||j.ok===false){alert(j.error||j.message||"Greenlight review failed");return;}
 await refresh();
},true);
</script>"""
    text=text.replace("</body>",ui+"</body>",1)

    # Add buttons to the rendered Greenlight NEEDS_REVIEW view.
    needle='Greenlight Review'
    # Generic post-render injection avoids coupling to a specific detail template.
    injector=r"""<script>
function lfGreenlightButtons(){
 const title=[...document.querySelectorAll("h1,h2,h3")].find(x=>x.textContent.trim()==="Greenlight Review");
 if(!title||document.getElementById("greenlight-actions-11410"))return;
 const pane=title.closest("aside,section,div");
 const episode=(document.body.innerText.match(/JP_BTS_EP\d+/)||[])[0];
 if(!pane||!episode)return;
 const box=document.createElement("div");box.id="greenlight-actions-11410";box.style.margin="12px 0";
 box.innerHTML='<button data-episode-id="'+episode+'" data-greenlight-decision="APPROVE">Approve Greenlight</button> <button data-episode-id="'+episode+'" data-greenlight-decision="HOLD">Hold</button> <button data-episode-id="'+episode+'" data-greenlight-decision="REJECT">Reject</button>';
 title.insertAdjacentElement("afterend",box);
}
setInterval(lfGreenlightButtons,500);
</script>"""
    text=text.replace("</body>",injector+"</body>",1)

    # Register POST endpoint in the stdlib HTTP handler by inserting before generic 404 in do_POST.
    # Fail build if known API anchor is absent, rather than ship an unverified route.
    route_anchor='def do_POST(self):'
    if route_anchor not in text:
        raise RuntimeError("v1.14.10 do_POST anchor missing")
    pos=text.index(route_anchor)
    bodypos=text.find("\n",pos)+1
    route=r'''        # greenlight-review-11410
        import re as _re
        _m=_re.fullmatch(r"/api/episodes/([^/]+)/greenlight-review", self.path.split("?",1)[0])
        if _m:
            try:
                import json as _json
                n=int(self.headers.get("Content-Length","0") or 0)
                body=_json.loads(self.rfile.read(n).decode("utf-8") or "{}")
                episode_id=_m.group(1)
                ep=ROOT/"projects"/"JP_BTS"/"episodes"/episode_id
                manifest=_json.loads((ep/"episode_manifest.json").read_text(encoding="utf-8"))
                from adapters.adapter_registry import get_adapter
                adapter=get_adapter(ROOT,manifest["authority"]["channel_adapter"])
                out=adapter.review_greenlight(episode_id,body.get("decision"),body.get("note",""))
                return self._json(200,out)
            except Exception as e:
                return self._json(400,{"ok":False,"error":str(e)})
'''
    text=text[:bodypos]+route+text[bodypos:]
'''
if anchor not in bt: raise SystemExit("runtime anchor missing")
bt=bt.replace(anchor,patch+anchor,1)
files[boot]=bt.encode()

m=json.loads(files["update_manifest.json"])
m["package_id"]="LONGFORM_FACTORY_GREENLIGHT_REVIEW_1_14_10"
m["version"]="1.14.10";m["from_versions"]=["1.14.9"]
m["title"]="Greenlight Review Actions"
m["summary"]="Adds explicit Approve, Hold and Reject actions for JP_BTS Greenlight Review and advances approved episodes to Editorial Ready."
for f in m["files"]:
    if f["source"] in files:f["sha256"]=sha(files[f["source"]])
files["update_manifest.json"]=(json.dumps(m,ensure_ascii=False,indent=2)+"\n").encode()
files["release_notes.md"]=files.get("release_notes.md",b"")+b"\n\n1.14.10: Add explicit JP_BTS Greenlight review actions; approval advances to Editorial Ready.\n"

with tempfile.TemporaryDirectory() as td:
 for n in [boot,ap]:
  p=Path(td)/Path(n).name;p.write_bytes(files[n]);py_compile.compile(str(p),doraise=True)
with zipfile.ZipFile(OUT,"w",zipfile.ZIP_DEFLATED) as z:
 for n,b in files.items():z.writestr(n,b)
with zipfile.ZipFile(OUT) as z:
 assert z.testzip() is None
 mm=json.loads(z.read("update_manifest.json"));assert mm["version"]=="1.14.10"
 for f in mm["files"]:assert sha(z.read(f["source"]))==f["sha256"]
 a=z.read(ap).decode(); b=z.read(boot).decode()
 assert "def review_greenlight(" in a and '"EDITORIAL","READY"' in a
 assert "greenlight-review-11410" in b and "Approve Greenlight" in b
 rr=json.loads(z.read("payload/adapters/adapter_registry.json"))
 assert rr["channels"]["JP_BTS"]["default_adapter"]=="JP_BTS_PRODUCTION_ADAPTER_v1_1"
 assert rr["channels"]["EN_BTS"]["default_adapter"]=="EN_BTS_PRODUCTION_ADAPTER_v1_2"

digest=sha(OUT.read_bytes())
feed={"schema":"LONGFORM_FACTORY_UPDATE_FEED_v1","generated_at":"AUTO","channels":{"dev":{"version":"1.14.10","package_url":"https://raw.githubusercontent.com/Kapka87/longform-factory-updates/main/packages/LONGFORM_FACTORY_GREENLIGHT_REVIEW_1_14_10.lfupdate.zip","package_sha256":digest,"updater_api_min":"1.1","published_at":"AUTO","title":"Greenlight Review Actions","summary":"Adds explicit Greenlight review actions and advances approved JP_BTS episodes to Editorial Ready."}},"cache_bust":"1.14.10-auto"}
Path("feed.v11410.json").write_text(json.dumps(feed,ensure_ascii=False,indent=2)+"\n")
print(json.dumps({"sha256":digest,"bytes":OUT.stat().st_size},indent=2))
